
                    <li><a href="list.php?fid=78">现货白银</a></li>
                    <li><a href="list.php?fid=122" class="cur">现货原油</a></li>
                    <li><a href="list.php?fid=81">现货铜</a></li>
                    <li><a href="list.php?fid=132">外汇兑换</a></li>
                </ul>
            </div><!--tit -->
        </div>
    </div>

    <div class="p_50_0 w_1200 clearfix">
        <div class="w_570 fl_left ta_c"><img src="{dede:global.cfg_templets_skin