<tr>
                            <td style="border-bottom:1px dotted #ccc;line-height:45px;background:url({dede:global.cfg_templets_skin/}/images/title_icon3.gif) no-repeat 0px 21px;padding-left:9px;">
                                <span style="float:left;">
                                    <a href="[field:arcurl/]">
                                        [field:title/]
                                    </a>
                                </span><span style="float:right;">(2016-03-10)</span>
                            </td>
                        </tr>