<?php
$z[0]=Array("field","",81,103);
$z[0][4]['name']="typelink";
$z[1]=Array("field","",114,136);
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n                            <li>\r\n                                <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                            </li>\r\n                            ",294,529);
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>