<?php
$z[0]=Array("global","",57,83);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",86,109);
$z[1][4]['name']="seotitle";
$z[2]=Array("global","",233,260);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",302,332);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",352,384);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",477,509);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",581,613);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",693,725);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1590,1622);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("include","",1702,1737);
$z[9][4]['filename']="head.htm";
$z[10]=Array("global","",1790,1822);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("channel","\r\n                        <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n                        ",2110,2342);
$z[11][4]['type']="son";
$z[11][4]['row']="9";
$z[11][4]['currentstyle']="<li><a href='~typelink~' class='on'>~typename~</a></li>";
$z[12]=Array("field","",2638,2659);
$z[12][4]['name']="content";
$z[13]=Array("include","",2769,2804);
$z[13][4]['filename']="foot.htm";

?>