<?php
$z[0]=Array("global","",57,83);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",207,234);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",276,306);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",326,358);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",451,483);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",555,587);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",667,699);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",1563,1595);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("include","",1675,1710);
$z[8][4]['filename']="head.htm";
$z[9]=Array("global","",1763,1795);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("channel","\r\n                        <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n                        ",2083,2315);
$z[10][4]['type']="son";
$z[10][4]['row']="9";
$z[10][4]['currentstyle']="<li><a href='~typelink~' class='on'>~typename~</a></li>";
$z[11]=Array("field","",2611,2632);
$z[11][4]['name']="content";
$z[12]=Array("include","",2742,2777);
$z[12][4]['filename']="foot.htm";

?>