<?php
$z[0]=Array("global","",144,176);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",2196,2228);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",2560,2592);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",2949,2976);
$z[3][4]['name']="cfg_indexurl";
$z[4]=Array("channelartlist","\r\n            <li>\r\n                <div class=\"navdiv\">\r\n                    <a href=\"javascript:void(0);\">{dede:field name='typename'/}</a>\r\n                </div>\r\n                <div class=\"navshow\" style=\"display: none;\">\r\n                    <ul>\r\n                        {dede:channel type='son' noself='yes'}\r\n                        <li>\r\n                            <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                        </li>\r\n                        {/dede:channel}\r\n                    </ul>\r\n                </div>\r\n            </li>\r\n            ",3065,3728);
$z[4][4]['typeid']="top";
$z[4][4]['cacheid']="channelsonlist";

?>