<?php
$z[0]=Array("global","",57,83);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",86,109);
$z[1][4]['name']="seotitle";
$z[2]=Array("global","",233,260);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",302,332);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",352,384);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",477,509);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",581,613);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",693,725);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",851,883);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1676,1708);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("include","",1788,1823);
$z[10][4]['filename']="head.htm";
$z[11]=Array("global","",1876,1908);
$z[11][4]['name']="cfg_templets_skin";
$z[12]=Array("channel","\r\n                        <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                        ",2195,2452);
$z[12][4]['type']="son";
$z[12][4]['row']="9";
$z[12][4]['currentstyle']="<li><a href='~typelink~' class='on'>~typename~</a></li>";
$z[13]=Array("list","\r\n                        <tr>\r\n                            <td style=\"border-bottom:1px dotted #ccc;line-height:45px;background:url(/templets/qhzjcy/images/title_icon3.gif) no-repeat 0px 21px;padding-left:9px;\">\r\n                                <span style=\"float:left;\">\r\n                                    <a href=\"[field:arcurl/]\">\r\n                                        [field:title/]\r\n                                    </a>\r\n                                </span><span style=\"float:right;\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>\r\n                            </td>\r\n                        </tr>\r\n                        ",2735,3434);
$z[13][4]['titlelen']="35";
$z[13][4]['pagesize']="20";
$z[14]=Array("pagelist","",3620,3686);
$z[14][4]['listsize']="5";
$z[14][4]['listitem']="index,end,pre,next,pageno";
$z[15]=Array("include","",3825,3860);
$z[15][4]['filename']="foot.htm";

?>